version: '2.4'
networks:
  dms-dws.cloud01.gobien.be:
       name: "dms-dws.cloud01.gobien.be"
       external: true

services:
  nginx:
    image: nginx
    container_name: web01
    logging:
      options:
        max-size: "10m"
        max-file: "3"    
    restart: always
    mem_limit: 256m
    memswap_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dms-dws.cloud01.gobien.be
    volumes:
      - /data/containers/webserverstack/config/nginx/conf.d:/etc/nginx/conf.d:Z
      - /data/containers/webserverstack/config/nginx/global:/etc/nginx/global:Z
      - /data/containers/webserverstack/config/nginx/templates:/etc/nginx/templates:Z
      - /data/containers/webserverstack/logs/nginx:/var/log/nginx:z      
      - /data/containers/webserverstack/data/certificates:/certificates:z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
    tmpfs:
      - /tmp
    depends_on:
      - db
      - php-fpm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      

  php-fpm:
    image: php:fpm
    container_name: php01
    logging:
      options:
        max-size: "10m"
        max-file: "3"        
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m
    links:
      - db
    networks:
      - dms-dws.cloud01.gobien.be      
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /data/containers/webserverstack/config/php-fpm/conf.d:/usr/local/etc/php/conf.d:Z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
      - /data/containers/webserverstack/config/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf.custom:Z
      - /data/containers/webserverstack/config/php-fpm/msmtprc:/etc/msmtprc.custom:Z      
      - /data/containers/webserverstack/scripts/entrypoint.sh:/bin/entrypoint.sh:Z
    entrypoint: /bin/entrypoint.sh
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
      
  db:
    image: mariadb
    container_name: db01
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog_format=MIXED --binlog-row-image=minimal --log_bin_compress=ON --expire-logs-days=5 --binlog-expire-logs-seconds=2592000 --max-binlog-size=5M --max-binlog-total-size=805306368 --slave-connections-needed-for-purge=0 --innodb-flush-log-at-trx-commit=1 --sync-binlog=1 --character-set-server=utf8
    logging:
      options:
        max-size: "10m"
        max-file: "3"        
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m    
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: default
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: ${DB_STACKNETWORK}
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    networks:
      - dms-dws.cloud01.gobien.be      
    volumes:
      - /data/containers/webserverstack/data/mysql:/var/lib/mysql:Z
      - /data/containers/webserverstack/backup/mysql:/backup:Z
      - /data/containers/webserverstack/config/mysql:/etc/mysql/conf.d:Z
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    logging:
      options:
        max-size: "10m"
        max-file: "3"        
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 512m   
    links:
      - db
    networks:
      - dms-dws.cloud01.gobien.be      
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1G
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8081:80
      
  acme.sh:
    image: neilpang/acme.sh:latest
    container_name: acme01
    logging:
      options:
        max-size: "10m"
        max-file: "3"        
    restart: always
    networks:
      - dms-dws.cloud01.gobien.be    
    volumes:
      - /data/containers/webserverstack/config/acme.sh/acme.sh-docker.sh:/acme.sh-docker.sh:ro
      - /data/containers/webserverstack/data/certificates:/acme.sh:z
    environment:
      ACME_HOME_DIR: "/acme.sh"
      # CloudFlare
      CF_Token: "${CF_TOKEN}"
      CF_Account_ID: "${CF_ACCOUNT_ID}"
      DNS_API: "dns_cf"
      DOMAIN_NAME: "${DOMAIN_NAME}"
      ACME_SH_EMAIL: "${EMAIL}"
    command: sh ./acme.sh-docker.sh
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
