version: '2.4'
services:
  nginx:
    image: nginx
    restart: always
    cpu_percent: 20 
    mem_limit: 256m
    memswap_limit: 512m
    environment:
      - AMPLIFY_IMAGENAME=docker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:Z
      - ./config/nginx/templates:/etc/nginx/templates:Z
      - ./logs:/var/log/nginx:Z      
      - ./data/nginx/certificates:/nginx/certificates:z
      - ./data/vhosts:/data/vhosts:z
    tmpfs:
      - /tmp
    depends_on:
      - db
      - php-fpm

php-fpm:
    image: php:8-fpm
    restart: always
    cpu_percent: 30 
    mem_limit: 512m
    memswap_limit: 1024m    
    volumes:
      - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini:Z
    tmpfs:
      - /tmp      
      
 db:
    image: mariadb
    restart: always
    cpu_percent: 20 
    mem_limit: 512m
    memswap_limit: 1024m    
    environment:
      MYSQL_ROOT_PASSWORD=notSecureChangeMe
    volumes:
      - ./data/mysql:/var/lib/mysql:Z
    tmpfs:
      - /tmp  

 phpmyadmin:
    image: phpmyadmin:fpm-alpine
    restart: always
    cpu_percent: 5 
    mem_limit: 256m
    memswap_limit: 512m    
    environment:
      PMA_ARBITRARY=1      
    volumes:
      - ./config/db/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:Z
    tmpfs:
      - /tmp      
    depends_on:
      - db
    ports:
      - "8080:80"
