version: '2.4'
services:
  nginx:
    image: nginx
    restart: always
    mem_limit: 256m
    memswap_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/containers/webserverstack/config/nginx/conf.d:/etc/nginx/conf.d:Z
      - /data/containers/webserverstack/config/nginx/global:/etc/nginx/global:Z
      - /data/containers/webserverstack/config/nginx/templates:/etc/nginx/templates:Z
      - /data/containers/webserverstack/logs/nginx:/var/log/nginx:Z      
      - /data/containers/webserverstack/data/certificates:/certificates:z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
    tmpfs:
      - /tmp
    depends_on:
      - db
      - php-fpm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      

  php-fpm:
  # https://docs.portainer.io/v/ce-2.9/faq/troubleshooting/can-i-build-an-image-while-deploying-a-stack-application-from-git
  # Workaround Use the link to the build file in the portainer build image editor and name it php-8-fpm-custom-ares:latest
  # Then deploy the stack succesfully
    build: https://raw.githubusercontent.com/Stan-Gobien/DockerWebserverStack/AresSvr/Docker-PHP-FPM/Dockerfile
    image: php-8-fpm-custom-ares:latest
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m
    links:
      - db
    volumes:
      - /data/containers/webserverstack/config/php-fpm/conf.d:/usr/local/etc/php/conf.d:Z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
      - /data/containers/webserverstack/config/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:Z
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=false"      
      
  db:
    image: mariadb
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m    
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: default
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: ${DB_STACKNETWORK}
    volumes:
      - /data/containers/webserverstack/data/mysql:/var/lib/mysql:Z
      - /data/containers/webserverstack/backup/mysql:/backup:Z
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 512m   
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1G
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8081:80
      
  acme.sh:
    image: neilpang/acme.sh:latest
    restart: always 
    volumes:
      - /data/containers/webserverstack/config/acme.sh/acme.sh-docker.sh:/acme.sh-docker.sh:ro
      - /data/containers/webserverstack/data/certificates:/acme.sh:z
    environment:
      ACME_HOME_DIR: "/acme.sh"
      # CloudFlare
      CF_Token: "${CF_TOKEN}"
      CF_Account_ID: "${CF_ACCOUNT_ID}"
      DNS_API: "dns_cf"
      DOMAIN_NAME: "${DOMAIN_NAME}"
      ACME_SH_EMAIL: "${EMAIL}"
    command: sh ./acme.sh-docker.sh
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
