version: '2.4'
networks:
  mailserver-webserver-network:
    external:
       name: mailserver-webserver-network
services:
  nginx:
    image: nginx
    restart: always
    mem_limit: 256m
    memswap_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mailserver-webserver-network
    volumes:
      - /data/containers/webserverstack/config/nginx/conf.d:/etc/nginx/conf.d:Z
      - /data/containers/webserverstack/config/nginx/global:/etc/nginx/global:Z
      - /data/containers/webserverstack/config/nginx/templates:/etc/nginx/templates:Z
      - /data/containers/webserverstack/logs/nginx:/var/log/nginx:Z      
      - /data/containers/webserverstack/data/certificates:/certificates:z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
    tmpfs:
      - /tmp
    depends_on:
      - db
      - php-fpm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      

  php-fpm:
    build: https://raw.githubusercontent.com/Stan-Gobien/Docker-PHP-FPM/main/Dockerfile
    image: php-8-fpm-custom-stan:latest
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m
    links:
      - db
    networks:
      - mailserver-webserver-network      
    volumes:
      - /data/containers/webserverstack/config/php-fpm/conf.d:/usr/local/etc/php/conf.d:Z
      - /data/containers/webserverstack/data/vhosts:/data/vhosts:z
      - /data/containers/webserverstack/config/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:Z
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
      
  db:
    image: mariadb
    restart: always
    mem_limit: 512m
    memswap_limit: 1024m    
    environment:
      MARIADB_ROOT_PASSWORD: notSecureChangeMe
      MARIADB_DATABASE: default
      MARIADB_USER: sqluser
      MARIADB_PASSWORD: usersql
    networks:
      - mailserver-webserver-network      
    volumes:
      - /data/containers/webserverstack/data/mysql:/var/lib/mysql:Z
      - /data/containers/webserverstack/backup/mysql:/backup:Z
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 512m   
    links:
      - db
    networks:
      - mailserver-webserver-network      
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1G
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8081:80
      
  acme.sh:
    image: neilpang/acme.sh:latest
    networks:
      - mailserver-webserver-network    
    volumes:
      - /data/containers/webserverstack/config/acme.sh/acme.sh-docker.sh:/acme.sh-docker.sh:ro
      - /data/containers/webserverstack/data/certificates:/acme.sh:z
    environment:
      ACME_HOME_DIR: "/acme.sh"
      # CloudFlare
      CF_Token: "0Lj2BZLzceZyza3U4-3xh4DlmwqyXvFVRM6x180o"
      CF_Account_ID: "25112ee878751d122d2efdb921b725fc"
      DNS_API: "dns_cf"
      DOMAIN_NAME: "gobien.be"
      ACME_SH_EMAIL: "stan@gobien.be"
    command: sh ./acme.sh-docker.sh
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
